[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "c577619c5243d36332e69e27d9427baabee2ebb1"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "3d314bebe4500b68a96736e127aef2131d16f8fbf15961aaae712853a1010262"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.2.0+0/IntelOpenMP.v2024.2.0.i686-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "27e3bab1470ce3ab2060f90602f3566d535251a6"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "98bf02abfdfc76ee747b338c180cc0271daa51cbbd2e4e3ca1a5452456387a27"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.2.0+0/IntelOpenMP.v2024.2.0.i686-w64-mingw32.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "2a0caa7722da25c0bd014fa307849d6d5d3cac35"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "9c98f43e707a3f1362ee8a0ed82c79450c5f95bcb43683dac690e5163548cc5b"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.2.0+0/IntelOpenMP.v2024.2.0.x86_64-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "87039b6abab72003bf6479942fb218d827b3bbc9"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "7845a52a1b8ab9a687455d46a7e491d934aaa4143c1ef80cc1cd37ba3ecc026e"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.2.0+0/IntelOpenMP.v2024.2.0.x86_64-w64-mingw32.tar.gz"
