[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "b675088839c67848b9caccc4f6211f0b5979820d"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "561505074a00a2501b413b90e0bb05e1b54060b8a6d5bca792c1ba5c79f1dbf4"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.1.0+0/IntelOpenMP.v2024.1.0.i686-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "8bbcceb2b8609aa0c729783c6c959e54094bb253"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "85ed08ccbf64126fc3fbe1a1a19b06d7d6aa73882f0985a8012e672f43256887"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.1.0+0/IntelOpenMP.v2024.1.0.i686-w64-mingw32.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "821b92b64083dd265ebb58553e927ecd3bce29fe"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "977dcf58369becb258d59b4878dd18a68c059892d4e4afe2ae1b312d9b7fcd4d"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.1.0+0/IntelOpenMP.v2024.1.0.x86_64-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "c04d0b3d18e5fcdf696745d217847f2fdcbea1ee"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "29e3fb4a82bafbb7269d94fa3d3cb3e2ebfc53041c59b0688bbc8fdd44c07037"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2024.1.0+0/IntelOpenMP.v2024.1.0.x86_64-w64-mingw32.tar.gz"
