[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "57930c36f8df34b4f16b543291fec09c746ff53a"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "23f28299d3f9f3360ea30d614b1106752f15e19f205f165382652ba039589978"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+1/IntelOpenMP.v2018.0.3.i686-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "af5451a08f7d66b1373e2623cd6377d18d422ce8"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "975a4bce57bb28602f51bae96feb0460bab522709c0cd3cfdda6c22d650badd4"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+1/IntelOpenMP.v2018.0.3.i686-w64-mingw32.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "3887f40c50b12123ca0dbb87ba00c19e3c19a217"
os = "macos"

    [[IntelOpenMP.download]]
    sha256 = "b66fa2da83a959913fede8972796ba2030c1ea462ba6cdc74048aabd0dfc74f1"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+1/IntelOpenMP.v2018.0.3.x86_64-apple-darwin.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "9e09f17eeafd1580038f1d4033b5cc401b4b5af3"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "33613b6de71b0629de679d4f535803e691d3689c3489f691227f5913f2aae6c6"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+1/IntelOpenMP.v2018.0.3.x86_64-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "bcc7353f0441dd8ee3798b35d4195b7b274a01b6"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "8c63a997eddd89e6069abc4a8fee88c91842cd0d171febe20778e4e7dd8f6ff8"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+1/IntelOpenMP.v2018.0.3.x86_64-w64-mingw32.tar.gz"
