[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "a4918c557d15fa18432d35e28b227516d482b875"
os = "macos"

    [[IntelOpenMP.download]]
    sha256 = "d9ec418930f39bd2b5ae0d7cdb1a0015abc1846bbab1c11a517889b6a8e6e216"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2023.2.0+0/IntelOpenMP.v2023.2.0.x86_64-apple-darwin.tar.gz"
[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "d148c026075870dd476b7284b7afcb9425985dfd"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "b6af8134a3c2771106b7852d74aa480d269e6d08b0fb9ad1b8a3fa704b728aba"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2023.2.0+0/IntelOpenMP.v2023.2.0.i686-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "i686"
git-tree-sha1 = "7bdad03e55cfdc183e465dfc3630e53334f37c76"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "103b9647ad9f3075543676b5181571d1c8214588a84a66be39b03446a7ca9dd5"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2023.2.0+0/IntelOpenMP.v2023.2.0.i686-w64-mingw32.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "7603a552d4e7d117efc681e6f3b6990eda727840"
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "74ea102aff2b5ec084b38bc7c12c85eff255bb50907813af14493e2a6995b6c0"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2023.2.0+0/IntelOpenMP.v2023.2.0.x86_64-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "0ca2685c24303902e65e0866846d3b5404e2c9c6"
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "7c91357ad63e81d8f7a085c813df821d2251d0f90a298a36ee012f232ab3c326"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2023.2.0+0/IntelOpenMP.v2023.2.0.x86_64-w64-mingw32.tar.gz"
