[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "4483b551bfefda4b91721e8ce30336775d2d7658"
lazy = true
libc = "glibc"
os = "linux"

    [[IntelOpenMP.download]]
    sha256 = "389ce2ce7c272622c0e716ecf9af88b387a6cb6d2d8b275cdcd183e9bed53394"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2025.0.4+0/IntelOpenMP.v2025.0.4.x86_64-linux-gnu.tar.gz"
[[IntelOpenMP]]
arch = "x86_64"
git-tree-sha1 = "87c04cd6024ac13d04b9f0e9695b9dbc54a38511"
lazy = true
os = "windows"

    [[IntelOpenMP.download]]
    sha256 = "886a72bd6f0cdcdab0b95c9a96bcde25bfe53d24518033d4f21b6fbfb820e0e3"
    url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2025.0.4+0/IntelOpenMP.v2025.0.4.x86_64-w64-mingw32.tar.gz"
